### ISSUE TITLE
Recommendation: move to nix-community

### ISSUE THREAD

**Issue by Mic92** [nix-community/redoxpkgs#1]
If you move this project to [nix-community](https://github.com/nix-community) you could make use of
our 1TB cachix cache to provide pre-compiled redoxpkgs.
There is also some build infrastructure (1 hetzner server atm).
If you use a the cache it would also make sense to pin nixpkgs.
Also it's easier to add additional maintainers to the project from there.

if you have further question join #nix-community on freenode.

**Comment by aaronjanse** [comment]
That would be fantastic! How can I move the repo? Simply transfer ownership to the nix-community organization?

**Comment by Mic92** [comment]
Yes.

**Comment by aaronjanse** [comment]
I tried:
> You don’t have the permission to create public repositories on nix-community

Maybe somehow nix-community now has a private copy?

**Comment by Mic92** [comment]
@aaronjanse I forgot to sent you an invite for the organization. After that you should be able to transfer.

**Comment by aaronjanse** [comment]
The transfer is complete. May nix-community have mercy on my code :pray:

**Comment by Mic92** [comment]
Ok. If you want access to the cachix community cache ask @zimbatm on irc.
