### ISSUE TITLE
The nixpkgs fork can not be fetched on Hydra 

### ISSUE THREAD

**Issue by nlewo** [nix-community/redoxpkgs#3]
The Hydra evaluator reports this error:
```
error: "access to URI 'https://github.com/aaronjanse/nixpkgs' is forbidden in restricted mode"
```
in https://hydra.nix-community.org/jobset/redoxpkgs/master#tabs-errors.

There is several ways to fix that, you can either
- update the Hydra jobset configuration to directly fetch your fork (hard to test) 
- or manually patch the upstream nixpkgs

I provide some detail for the latter option.
Instead of fetching your fork (with `fetchGit`), you could fetch the upstream nixpkgs, copy your patches in your repository and apply them on the upstream nixpkgs.
Note you can use a nixpkgs provided by Hydra in your `default.nix`.

**Comment by aaronjanse** [comment]
> Note you can use a nixpkgs provided by Hydra in your default.nix.

This one is slightly too old; it doesn't have the Redox PR in it. I just pushed a commit using a pinned version of Nixpkgs. As far as I can tell, it looks like the Hydra build is working now?

**Comment by aaronjanse** [comment]
Ah nvm. I can't tell what's going on

**Comment by nlewo** [comment]
Fixed by https://github.com/nix-community/redoxpkgs/commit/679b890e74dc730e89e1f79af5e94f9db50dc247
